- name: Allow SSH in UFW
  ufw: rule=allow port=22 proto=tcp

- name: Allow SSH in UFW
  ufw: rule=allow port=51820 proto=udp  

- name: install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present


- name: Enable net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: yes
    state: present  